#!/usr/bin/env bash
#
# pr-monitor.sh — poll a GitHub (Enterprise) PR and emit one line per event, for use with
# Claude Code's Monitor tool during an autonomous review cycle.
#
# Ships with the launcher instead of being regenerated by the review agent each session, so
# the loop is deterministic and testable rather than hand-rolled differently every time.
#
# Usage:
#   pr-monitor.sh --host <ghes-host> --repo <owner/name> --pr <number>
#                 [--since <ISO8601 UTC>] [--interval <seconds>] [--once]
#
#   --since    only comments/review-comments/reviews created strictly after this UTC
#              timestamp are reported (default: the time the monitor starts).
#   --interval seconds between poll cycles (default: 30).
#   --once     emit the first event line and exit 0 (for harnesses that only re-invoke the
#              agent on process exit, e.g. a background Bash task when the Monitor tool is
#              absent). Default is keep-running for mid-flight events so Claude Code's
#              Monitor tool can notify on each stdout line.
#
# Behavior:
#   - Emits a line and EXITS 0 when the PR is merged or closed.
#   - Without --once: emits a line and KEEPS RUNNING when the head commit changes, or when
#     an issue comment, review comment, or review from anyone other than the authenticated
#     gh user lands after --since.
#   - With --once: emits the first such mid-flight event line and EXITS 0 (same as
#     merge/close), so a background Bash task completes and wakes the agent.
#   - Tolerates transient gh/network failures without exiting (exits 1 only when the first
#     poll gets a definitive 401/403/404, i.e. bad auth or a PR that doesn't exist).
#   - Uses ETag conditional requests for PR state and paginates feedback. gh exits non-zero on
#     a 304 while still printing the response headers, so the parsed HTTP status line is
#     authoritative here — never gh's exit code.
#
# stdout is the event stream (one line per event); diagnostics go to stderr.
# Set PR_MONITOR_DEBUG=1 for per-cycle status lines on stderr.
#
# Runs in the Linux development host under bash 5 with GNU coreutils. It is deliberately written
# against plain POSIX-ish bash (no associative arrays, no namerefs) so it stays readable and
# easy to test; there is no compatibility target beyond that.

set -u

HOST="" REPO="" PR="" SINCE="" INTERVAL=30 ONCE=0

usage() {
  echo "usage: $0 --host <ghes-host> --repo <owner/name> --pr <number> [--since <ISO8601 UTC>] [--interval <seconds>] [--once]" >&2
  exit 2
}

# Emit one event line to stdout; with --once, exit 0 immediately after.
emit() {
  echo "$1"
  [ "$ONCE" = "1" ] && exit 0
  return 0
}

while [ $# -gt 0 ]; do
  case "$1" in
    --once)
      ONCE=1
      shift
      ;;
    --host|--repo|--pr|--since|--interval)
      [ $# -ge 2 ] || usage
      case "$1" in
        --host)     HOST="$2" ;;
        --repo)     REPO="$2" ;;
        --pr)       PR="$2" ;;
        --since)    SINCE="$2" ;;
        --interval) INTERVAL="$2" ;;
      esac
      shift 2
      ;;
    *) usage ;;
  esac
done

case "$HOST" in *[!A-Za-z0-9.-]*|"") usage ;; esac
[[ "$REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || usage
case "${REPO%/*}" in .|..) usage ;; esac
case "${REPO#*/}" in .|..) usage ;; esac
case "$PR" in *[!0-9]*|"") usage ;; esac
case "$INTERVAL" in *[!0-9]*|""|0) usage ;; esac
if [ -n "$SINCE" ]; then
  case "$SINCE" in
    [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]Z) ;;
    *) echo "pr-monitor: --since must be an ISO8601 UTC timestamp like 2026-01-31T12:00:00Z" >&2; exit 2 ;;
  esac
fi

for dep in gh jq; do
  command -v "$dep" >/dev/null 2>&1 || { echo "pr-monitor: required dependency '$dep' not found in PATH" >&2; exit 1; }
done

ME="$(gh api --hostname "$HOST" user --jq .login 2>/dev/null || true)"
if [ -z "$ME" ]; then
  echo "pr-monitor: cannot resolve the authenticated gh user for $HOST (check gh auth status)" >&2
  exit 1
fi

[ -n "$SINCE" ] || SINCE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

WORK="$(mktemp -d "${TMPDIR:-/tmp}/pr-monitor.XXXXXX")" || exit 1
trap 'rm -rf "$WORK"' EXIT

debug() {
  [ "${PR_MONITOR_DEBUG:-0}" = "1" ] && echo "pr-monitor: $*" >&2
  return 0
}

# fetch <api-path> <stored-etag>
# Sets FETCH_STATUS to the parsed HTTP status ("" if no response arrived) and, on 200,
# refreshes FETCH_ETAG and writes the response body to $WORK/body.json.
FETCH_STATUS="" FETCH_ETAG=""
fetch() {
  local api_path="$1" etag="$2" raw="$WORK/raw.http"
  FETCH_STATUS="" FETCH_ETAG="$etag"
  local args=(api --hostname "$HOST" "$api_path" --include)
  [ -n "$etag" ] && args+=(-H "If-None-Match: $etag")
  # gh exits non-zero on any non-2xx (including 304) but still prints the response;
  # parse the status line instead of trusting the exit code.
  gh "${args[@]}" >"$raw" 2>/dev/null || true
  # Split the raw response into the real header block ($WORK/hdr) and body
  # ($WORK/body.json) in a single pass. `--include` concatenates headers and
  # body, and a proxy/HTTP stack may prepend informational (1xx) or
  # `... Connection established` CONNECT blocks, so a naive `grep '^HTTP/'` over
  # the whole file can latch onto a preamble line — or, once past the headers,
  # onto a body line that merely starts with `HTTP/`. This state machine skips
  # leading 1xx/CONNECT preamble blocks, records only the real status + header
  # lines, and switches to the body on the blank line ending the real header
  # block — after which it is a one-way latch (body `HTTP/` lines are copied
  # verbatim, never re-interpreted as a new header block).
  : >"$WORK/hdr"; : >"$WORK/body.json"
  awk '
    BEGIN { state="seek" }                    # seek -> inhdr -> inbody (one-way)
    state=="inbody" { print > BODY; next }
    /^HTTP\// {
      if ($2 ~ /^1[0-9][0-9]$/ || $0 ~ /Connection established/) { skip=1 }
      else { skip=0; print > HDR }            # keep the real status line
      state="inhdr"; next
    }
    state=="inhdr" && /^\r?$/ { if (skip) state="seek"; else state="inbody"; next }
    state=="inhdr" { if (!skip) print > HDR; next }
  ' HDR="$WORK/hdr" BODY="$WORK/body.json" "$raw"
  FETCH_STATUS="$(grep -a '^HTTP/' "$WORK/hdr" | tail -n 1 | awk '{print $2}')"
  if [ "$FETCH_STATUS" = "200" ]; then
    FETCH_ETAG="$(grep -ai '^etag:' "$WORK/hdr" | tail -n 1 | sed -e 's/^[^:]*:[[:space:]]*//' -e 's/'$'\r''$//')"
  fi
}

# Dedup already-reported comment/review ids (string scan — bash 3.2 has no assoc arrays).
SEEN="|"
seen() { case "$SEEN" in *"|$1|"*) return 0 ;; *) return 1 ;; esac; }
mark() { SEEN="$SEEN$1|"; }

ET_PULL=""
HEAD_SHA=""
FIRST_CYCLE=1

check_pull() {
  fetch "repos/$REPO/pulls/$PR" "$ET_PULL"
  debug "pulls: HTTP ${FETCH_STATUS:-none}"
  if [ "$FIRST_CYCLE" = "1" ]; then
    case "$FETCH_STATUS" in
      401|403|404)
        echo "pr-monitor: repos/$REPO/pulls/$PR returned HTTP $FETCH_STATUS on the first poll (bad auth or nonexistent PR)" >&2
        exit 1 ;;
    esac
  fi
  [ "$FETCH_STATUS" = "200" ] || return 0
  ET_PULL="$FETCH_ETAG"
  jq -e . "$WORK/body.json" >/dev/null 2>&1 || return 0
  local merged state head
  merged="$(jq -r '.merged_at // empty' "$WORK/body.json")"
  state="$(jq -r '.state // empty' "$WORK/body.json")"
  head="$(jq -r '.head.sha // empty' "$WORK/body.json")"
  if [ -n "$merged" ]; then
    echo "PR #$PR MERGED at $merged"
    exit 0
  fi
  if [ "$state" = "closed" ]; then
    echo "PR #$PR CLOSED (not merged)"
    exit 0
  fi
  if [ -n "$head" ] && [ -n "$HEAD_SHA" ] && [ "$head" != "$HEAD_SHA" ]; then
    emit "PR #$PR NEW COMMIT: head ${HEAD_SHA:0:8} -> ${head:0:8}"
  fi
  [ -n "$head" ] && HEAD_SHA="$head"
  return 0
}

# check_list <api-path> <key: IC|RC|RV> <jq filter producing "<id>\t<event text>" rows>
check_list() {
  local api_path="$1" key="$2" filter="$3" id text
  # Fetch every page: the reviews endpoint is chronological and a changed last
  # page need not change the first page's ETag.
  gh api --hostname "$HOST" "$api_path" --paginate --slurp >"$WORK/pages.json" 2>/dev/null || return 0
  jq -e 'add // []' "$WORK/pages.json" >"$WORK/body.json" 2>/dev/null || return 0
  while IFS=$'\t' read -r id text; do
    [ -n "$id" ] || continue
    seen "$key:$id" && continue
    mark "$key:$id"
    emit "$text"
  done < <(jq -r --arg me "$ME" --arg since "$SINCE" --arg pr "$PR" "$filter" "$WORK/body.json" 2>/dev/null)
}

# In the filters below, $me/$since/$pr are jq variables (passed via --arg), not shell.
# shellcheck disable=SC2016
FILTER_IC='.[] | select(.user.login != $me and .created_at > $since)
  | "\(.id)\tPR #\($pr) NEW COMMENT from \(.user.login) at \(.created_at)"'
# shellcheck disable=SC2016
FILTER_RC='.[] | select(.user.login != $me and .created_at > $since)
  | "\(.id)\tPR #\($pr) NEW REVIEW COMMENT from \(.user.login) at \(.created_at)"'
# shellcheck disable=SC2016
FILTER_RV='.[] | select(.user.login != $me and (.submitted_at // "") > $since)
  | "\(.id)\tPR #\($pr) NEW REVIEW (\(.state)) from \(.user.login) at \(.submitted_at)"'

while true; do
  check_pull
  # All feedback pages are checked, including PRs with more than 100 reviews.
  check_list "repos/$REPO/issues/$PR/comments?per_page=100&sort=created&direction=desc" IC "$FILTER_IC"
  check_list "repos/$REPO/pulls/$PR/comments?per_page=100&sort=created&direction=desc" RC "$FILTER_RC"
  check_list "repos/$REPO/pulls/$PR/reviews?per_page=100" RV "$FILTER_RV"
  FIRST_CYCLE=0
  sleep "$INTERVAL"
done
